### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nojaf** [w0rm/creating-a-fun-game-with-elm#2]
So I just saw [this tweet](https://twitter.com/rtfeldman/status/973382389035618304) and Richard was spot on: amazing image! Could I use this image in my own presentation please?

**Comment by w0rm** [comment]
@nojaf hey! I'm not sure how this art should be licensed. I think it should be fine if you provide a link to Kolja (he is https://twitter.com/01k on Twitter). 

/cc @kolja
